# Generated by Django 3.1.3 on 2020-12-25 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(default='test', max_length=20),
            preserve_default=False,
        ),
    ]
