# Generated by Django 3.1.3 on 2021-03-20 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210320_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='title',
            field=models.CharField(default='Test title', max_length=50),
            preserve_default=False,
        ),
    ]
