# Generated by Django 3.1.3 on 2021-01-15 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='avatar',
            field=models.ImageField(default='/static/no-avatar.png', upload_to='users/%Y/%m/%d/'),
        ),
    ]
