# Generated by Django 3.1.3 on 2021-01-15 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20210115_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='avatar',
            field=models.ImageField(default='/Users/damiantabor/projects/my_projects/network/media//static/no-avatar.png', upload_to='users/%Y/%m/%d/'),
        ),
    ]
