# Generated by Django 3.1.3 on 2021-03-22 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20210320_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='facebook_url',
            field=models.URLField(default='http://example.com', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='github_url',
            field=models.URLField(default='http://example.com', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter_url',
            field=models.URLField(default='http://example.com', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='youtube_url',
            field=models.URLField(default='http://example.com', max_length=40),
            preserve_default=False,
        ),
    ]
