# Generated by Django 3.1.3 on 2021-01-16 22:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20210115_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatar',
            name='added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
