# Generated by Django 3.1.3 on 2021-01-16 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_avatar_added'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avatar',
            options={'ordering': ['added']},
        ),
    ]
