# Generated by Django 3.1.3 on 2021-03-10 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gify', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
    ]
