# Generated by Django 3.1.3 on 2021-04-01 10:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gify', '0005_auto_20210316_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user_likes',
            field=models.ManyToManyField(blank=True, related_name='posts_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
