# Generated by Django 3.1.3 on 2021-04-01 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_profile_following'),
        ('gify', '0006_post_user_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='user_likes',
            field=models.ManyToManyField(blank=True, related_name='posts_likes', to='account.Profile'),
        ),
    ]
