# Generated by Django 3.1.3 on 2021-04-10 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gify', '0008_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
