# Generated by Django 3.1.3 on 2021-04-12 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gify', '0009_action_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='comment',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
